'use client'
import { useState } from 'react'
import { useData } from '@/components/data-provider'
import { C, MO, Bg, Btn, Inp, Tbl, Tbs, Ety, Modal, isoToday } from '@/components/ui'

function CycleForm({n,onSave}){const[nm,setNm]=useState('');const[tp,setTp]=useState('quarterly');const[st,setSt]=useState(isoToday());const[en,setEn]=useState('');return<div style={{display:'flex',flexDirection:'column',gap:12}}><Inp label="Name" value={nm} onChange={setNm} placeholder="Q1 Review" required/><Inp label="Type" value={tp} onChange={setTp} options={['quarterly','annual','360','probation']}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><Inp label="Start" value={st} onChange={setSt} type="date"/><Inp label="End" value={en} onChange={setEn} type="date"/></div><div style={{fontSize:11,color:C.txD}}>{n} active employees</div><Btn v="primary" onClick={()=>nm&&onSave({name:nm,type:tp,start_date:st,end_date:en})} disabled={!nm} style={{width:'100%',justifyContent:'center'}}>Create</Btn></div>}
function ReviewForm({employees,cycles,onSave}){const ac=employees.filter(e=>e.status==='active');const[ei,setEi]=useState(ac[0]?.id||'');const[ci,setCi]=useState(cycles[0]?.id||'');const[rv,setRv]=useState('');const[sc,setSc]=useState('4');const[fb,setFb]=useState('');const emp=employees.find(e=>e.id===ei);return<div style={{display:'flex',flexDirection:'column',gap:12}}><Inp label="Employee" value={ei} onChange={setEi} options={ac.map(e=>({value:e.id,label:e.name}))}/>{cycles.length>0&&<Inp label="Cycle" value={ci} onChange={setCi} options={cycles.map(c=>({value:c.id,label:c.name}))}/>}<Inp label="Reviewer" value={rv} onChange={setRv} placeholder="Name"/><Inp label="Score (1-5)" value={sc} onChange={v=>setSc(String(Math.max(1,Math.min(5,Number(v)))))} type="number"/><Inp label="Feedback" value={fb} onChange={setFb} textarea required/><Btn v="primary" onClick={()=>fb&&onSave({employee_id:ei,employee_name:emp?.name,cycle_id:ci||null,reviewer:rv,score:Number(sc),feedback:fb})} disabled={!fb} style={{width:'100%',justifyContent:'center'}}>Submit</Btn></div>}

export default function PerfPage(){const{emps,cycles,reviews,addCycle,addRev}=useData();const[tab,setTab]=useState('cycles');const[modal,setModal]=useState(null);return<div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h1 style={{fontSize:20,fontWeight:700}}>Performance</h1><div style={{display:'flex',gap:6}}><Btn v="ghost" sz="sm" icon="plus" onClick={()=>setModal('cycle')}>Cycle</Btn><Btn v="primary" sz="sm" icon="plus" onClick={()=>setModal('review')}>Review</Btn></div></div><Tbs tabs={[{id:'cycles',label:'Cycles',count:cycles.length},{id:'reviews',label:'Reviews',count:reviews.length}]} active={tab} onChange={setTab}/>{tab==='cycles'&&<Tbl cols={[{label:'Cycle',render:r=><span style={{fontWeight:500}}>{r.name}</span>},{label:'Type',render:r=><Bg v="dim">{r.type}</Bg>},{label:'Progress',render:r=><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{flex:1,height:5,background:C.bd,borderRadius:3,overflow:'hidden',minWidth:60}}><div style={{height:'100%',width:`${r.total?(r.completed/r.total*100):0}%`,background:r.completed===r.total?C.gn:C.cy,borderRadius:3}}/></div><span style={{fontFamily:MO,fontSize:10,color:C.txD}}>{r.completed}/{r.total}</span></div>}]} data={cycles} empty={<Ety icon="star" message="No cycles" action="Create" onAction={()=>setModal('cycle')}/>}/>}{tab==='reviews'&&<Tbl cols={[{label:'Employee',render:r=><span style={{fontWeight:500}}>{r.employee_name}</span>},{label:'Score',render:r=><span style={{fontFamily:MO,fontWeight:700,color:r.score>=4?C.gn:r.score>=3?C.am:C.rs}}>{r.score}/5</span>},{label:'Feedback',render:r=><span style={{fontSize:11,color:C.txM}}>{(r.feedback||'').slice(0,80)}</span>}]} data={reviews} empty={<Ety icon="star" message="No reviews" action="Write" onAction={()=>setModal('review')}/>}/>}<Modal open={modal==='cycle'} onClose={()=>setModal(null)} title="Review Cycle"><CycleForm n={emps.filter(e=>e.status==='active').length} onSave={async d=>{await addCycle(d);setModal(null)}}/></Modal><Modal open={modal==='review'} onClose={()=>setModal(null)} title="Write Review"><ReviewForm employees={emps} cycles={cycles} onSave={async d=>{await addRev(d);setModal(null)}}/></Modal></div>}
